return {
  "AstroNvim/astroui",
  opts = {
    -- Neovim 0.12 ships Catppuccin: dark background selects Mocha.
    colorscheme = "catppuccin",
    highlights = {
      catppuccin = {
        Normal = { fg = "#cdd6f4", bg = "NONE", ctermbg = "NONE" },
        NormalNC = { link = "Normal" },
        SignColumn = { fg = "#45475a", bg = "NONE", ctermbg = "NONE" },
        LineNr = { fg = "#45475a", bg = "NONE", ctermbg = "NONE" },
        EndOfBuffer = { fg = "#45475a", bg = "NONE", ctermbg = "NONE" },
        -- Core fallbacks are used by sidebars, inactive windows and Heirline.
        StatusLine = { fg = "#cdd6f4", bg = "NONE", ctermbg = "NONE" },
        StatusLineNC = { fg = "#a6adc8", bg = "NONE", ctermbg = "NONE" },
        StatusLineTerm = { link = "StatusLine" },
        StatusLineTermNC = { link = "StatusLineNC" },
        TabLine = { fg = "#a6adc8", bg = "NONE", ctermbg = "NONE" },
        TabLineFill = { link = "Normal" },
        WinBar = { link = "Normal" },
        WinBarNC = { link = "NormalNC" },
        TitleBar = { link = "Normal" },
        TitleBarNC = { link = "NormalNC" },
        FoldColumn = { fg = "#585b70", bg = "NONE", ctermbg = "NONE" },
        NeoTreeNormal = { link = "Normal" },
        NeoTreeNormalNC = { link = "NormalNC" },
        NeoTreeEndOfBuffer = { link = "EndOfBuffer" },
        -- Neo-tree otherwise synthesizes opaque tab/title backgrounds.
        NeoTreeTabInactive = { fg = "#a6adc8", bg = "NONE", ctermbg = "NONE" },
        NeoTreeTabSeparatorInactive = { fg = "#45475a", bg = "NONE", ctermbg = "NONE" },
        NeoTreeTabSeparatorActive = { fg = "#585b70", bg = "NONE", ctermbg = "NONE" },
        NeoTreeTitleBar = { link = "FloatTitle" },
        NeoTreeFloatTitle = { link = "FloatTitle" },
        NormalFloat = { fg = "#cdd6f4", bg = "NONE", ctermbg = "NONE" },
        FloatBorder = { fg = "#585b70", bg = "NONE", ctermbg = "NONE" },
        FloatTitle = { fg = "#b4befe", bg = "NONE", ctermbg = "NONE", bold = true },
        FloatFooter = { link = "FloatTitle" },
        WinSeparator = { fg = "#45475a", bg = "NONE", ctermbg = "NONE" },
        Pmenu = { fg = "#cdd6f4", bg = "NONE", ctermbg = "NONE" },
        PmenuExtra = { link = "Pmenu" },
        PmenuSbar = { bg = "NONE", ctermbg = "NONE" },
        PmenuSel = { fg = "#cdd6f4", bg = "#45475a", bold = true },
        SnacksPickerMatch = { fg = "#b4befe", bold = true },
        SnacksNormal = { link = "NormalFloat" },
        SnacksNormalNC = { link = "NormalFloat" },
        SnacksPicker = { link = "NormalFloat" },
        SnacksPickerBorder = { link = "FloatBorder" },
        SnacksPickerTitle = { link = "FloatTitle" },
        SnacksInputNormal = { link = "NormalFloat" },
        SnacksInputBorder = { link = "FloatBorder" },
        SnacksInputTitle = { link = "FloatTitle" },
        BlinkCmpMenu = { link = "Pmenu" },
        BlinkCmpMenuBorder = { link = "FloatBorder" },
        BlinkCmpMenuSelection = { link = "PmenuSel" },
        BlinkCmpDoc = { link = "NormalFloat" },
        BlinkCmpDocBorder = { link = "FloatBorder" },
        BlinkCmpSignatureHelp = { link = "NormalFloat" },
        BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
      },
    },
    status = {
      -- Rounded segments are part of the user's theme, including after reloads.
      separators = { left = { "", "" }, right = { "", "" }, center = { "", "" } },
      colors = {
        fg = "#cdd6f4", bg = "NONE",
        mode_fg = "#11111b", -- Do not derive mode text from the now-transparent StatusLine background.
        normal = "#cba6f7", insert = "#a6e3a1", visual = "#cba6f7",
        replace = "#f38ba8", command = "#f9e2af", terminal = "#94e2d5",
        git_branch_fg = "#cdd6f4", git_branch_bg = "#313244",
        file_info_bg = "#313244", nav_bg = "#313244",
        tabline_bg = "NONE", buffer_active_bg = "#313244",
        buffer_active_fg = "#b4befe", buffer_visible_bg = "NONE",
        buffer_visible_fg = "#cdd6f4", buffer_bg = "NONE", buffer_fg = "#a6adc8",
      },
    },
  },
}
